Created github

diff --git a/hueBrightness b/hueBrightness
--- a/hueBrightness
+++ b/hueBrightness
@@ -1,5 +1,5 @@
 #!/bin/bash
-[[ ! -d ~/.HueControl ]] && echo "Setup not found! Please run: hueConfig" && exit 1
+[[ ! -d ~/.HueControl ]] && echo "Setup not found! Please run: hueSetup" && exit 1
 [[ "$1" -eq "" ]] && echo "No ID Provided. Expected: hueBrightness <id> <brightness>" && exit 1
 [[ "$2" -eq "" ]] && echo "No brightness value provided! Expected hueBrightness <id> <brightness>" && exit 1
 echo "Turning light $1 on with brightness $2"
diff --git a/hueDelete b/hueDelete
--- a/hueDelete
+++ b/hueDelete
@@ -1,5 +1,5 @@
 #!/bin/bash
-[[ ! -d ~/.HueControl ]] && echo "Setup not found! Please run: hueConfig" && exit 1
+[[ ! -d ~/.HueControl ]] && echo "Setup not found! Please run: hueSetup" && exit 1
 [[ "$1" -eq "" ]] && echo "No ID Provided. Expected: hueDelete <id>" && exit 1
 echo "Deleting light $1"
 curl -s -XDELETE $(cat ~/.HueControl/address)/api/$(cat ~/.HueControl/username)/lights/$1 --data '{"on":true}' > /dev/null
diff --git a/hueList b/hueList
--- a/hueList
+++ b/hueList
@@ -1,5 +1,5 @@
 #!/bin/bash
-[[ ! -d ~/.HueControl ]] && echo "Setup not found! Please run: hueConfig" && exit 1
+[[ ! -d ~/.HueControl ]] && echo "Setup not found! Please run: hueSetup" && exit 1
 echo "Getting a list of bulbs"
 Bulbs=$(curl -s -XGET $(cat ~/.HueControl/address)/api/$(cat ~/.HueControl/username)/lights)
 echo $Bulbs | jq 'keys[] as $k | { ID: $k, Name: .[$k].name }'
diff --git a/hueScan b/hueScan
--- a/hueScan
+++ b/hueScan
@@ -1,5 +1,5 @@
 #!/bin/bash
-[[ ! -d ~/.HueControl ]] && echo "Setup not found! Please run: hueConfig" && exit 1
+[[ ! -d ~/.HueControl ]] && echo "Setup not found! Please run: hueSetup" && exit 1
 echo "Scanning for new lights, this process lasts for 40 seconds. Setting up lights may take longer than this so repeat the process until all lights are found."
 curl -s -XPOST $(cat ~/.HueControl/address)/api/$(cat ~/.HueControl/username)/lights > /dev/null
 
diff --git a/hueSetup b/hueSetup
--- a/hueSetup
+++ b/hueSetup
@@ -1,17 +1,26 @@
 #!/bin/bash
 clear
-echo "Hue config"
+echo "Hue setup"
+echo "To manually define the address (for connections without internet access) use: hueSetup -m"
 [[ -d ~/.HueControl ]] && echo "Configuration directory already exists! Only continue if you wish to generate a new configuration! CTRL+C to exit!"
 
-echo -n "Hue Bridge address: "
-read; Address="${REPLY}"
+echo
+if (( "$1" -eq "-m" )); then
+	echo -n "Hue Bridge address: "
+	read; Address="${REPLY}"
+else
+	echo "Getting Hue Bridge address from the broker server!"
+	Address=$(curl -s -XGET https://discovery.meethue.com/ | jq .[0].internalipaddress)
+	[[ "$Address" -eq "null" ]] && echo "Failed to contact broker server. Ensure that you and your Hue Bridge are connected to the internet!" && exit 1
+	echo "Detected address: $Address"
+fi
 
 echo
 echo "Generating username"
 response=$(curl -s -XPOST --url ${Address}/api --data "{\"devicetype\":\"HueLinuxRF $(whoami)@$(hostname)\"}")
 
 error=$(echo "$response" | jq .[0].error.type)
-[[ "$error" != "null" ]] && echo "Error! Ensure that you have pressed the connect button on the top of your hue unit!" && exit 1
+[[ "$error" != "null" ]] && echo "Error! Ensure that you have pressed the connect button on the top of your Hue Bridge unit!" && exit 1
 
 Username=$(echo "$response" | jq .[0].success.username)
 
